In [1]:
import torch

In [2]:
input_ids=torch.tensor([2,3,5,1])

In [3]:
vocab_size=6
output_dim=3
torch.manual_seed(123)
embedding_layer=torch.nn.Embedding(vocab_size,output_dim)

In [4]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [5]:
print(embedding_layer)

Embedding(6, 3)


In [6]:
embedding_layer(torch.tensor([3]))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)

In [7]:
embedding_layer(input_ids)

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)

# Understanding the difference between Embedding Layers and Linear Layers

In [8]:
idx=torch.tensor([2,3,5,1])
num_idx=max(idx)+1
out_dim=5

In [9]:
torch.manual_seed(123)
embedding=torch.nn.Embedding(num_idx,out_dim)

In [10]:
embedding.weight

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486],
        [ 0.6603, -0.2196, -0.3792,  0.7671, -1.1925],
        [ 0.6984, -1.4097,  0.1794,  1.8951,  1.3689],
        [-1.6033, -1.3250,  0.1784, -2.1338,  1.0524],
        [-0.3885, -0.9343,  1.8319, -0.3378,  0.8805],
        [ 1.5542,  0.6266, -0.1755,  0.0983, -0.0935]], requires_grad=True)

In [11]:
embedding(torch.tensor([1]))

tensor([[ 0.6603, -0.2196, -0.3792,  0.7671, -1.1925]],
       grad_fn=<EmbeddingBackward0>)

In [12]:
embedding(torch.tensor([2]))

tensor([[ 0.6984, -1.4097,  0.1794,  1.8951,  1.3689]],
       grad_fn=<EmbeddingBackward0>)

In [13]:
idx = torch.tensor([2, 3, 1])
embedding(idx)

tensor([[ 0.6984, -1.4097,  0.1794,  1.8951,  1.3689],
        [-1.6033, -1.3250,  0.1784, -2.1338,  1.0524],
        [ 0.6603, -0.2196, -0.3792,  0.7671, -1.1925]],
       grad_fn=<EmbeddingBackward0>)

# using nn.linear

In [14]:
onehot = torch.nn.functional.one_hot(idx)
onehot

tensor([[0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 1, 0, 0]])

In [15]:
num_idx = max(idx)+1

# The desired embedding dimension is a hyperparameter
out_dim = 5

In [16]:
num_idx

tensor(4)

In [17]:
out_dim

5

In [27]:
embedding=torch.nn.Embedding(num_idx,out_dim)

In [28]:
torch.manual_seed(123)
linear = torch.nn.Linear(4, 5, bias=False)
linear.weight

Parameter containing:
tensor([[-0.2039,  0.0166, -0.2483,  0.1886],
        [-0.4260,  0.3665, -0.3634, -0.3975],
        [-0.3159,  0.2264, -0.1847,  0.1871],
        [-0.4244, -0.3034, -0.1836, -0.0983],
        [-0.3814,  0.3274, -0.1179,  0.1605]], requires_grad=True)

In [29]:
linear.weight = torch.nn.Parameter(embedding.weight.T)

In [30]:
linear.weight

Parameter containing:
tensor([[ 1.5810,  0.2492, -0.9620, -1.7018],
        [ 1.3010, -0.4845,  1.2825, -0.7498],
        [ 1.2753, -2.0929, -0.3430, -1.1285],
        [-0.2010, -0.8199, -0.6821,  0.4135],
        [ 0.9624, -0.4210, -0.9887,  0.2892]], requires_grad=True)

In [31]:
linear(onehot.float())

tensor([[-0.9620,  1.2825, -0.3430, -0.6821, -0.9887],
        [-1.7018, -0.7498, -1.1285,  0.4135,  0.2892],
        [ 0.2492, -0.4845, -2.0929, -0.8199, -0.4210]], grad_fn=<MmBackward0>)

In [32]:
embedding(idx)

tensor([[-0.9620,  1.2825, -0.3430, -0.6821, -0.9887],
        [-1.7018, -0.7498, -1.1285,  0.4135,  0.2892],
        [ 0.2492, -0.4845, -2.0929, -0.8199, -0.4210]],
       grad_fn=<EmbeddingBackward0>)